command_timeout = 1000

# Disable the blank line at the start of the prompt
add_newline = false

[gcloud]
symbol = 'ï¸ğŸ‡¬ï¸ '


[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
symbol = 'ó°¸  '
